### ISSUE TITLE
Some courses are missing from sis, check out why and make sure they work in Suotar

### ISSUE THREAD

**Issue by saarasat** [UniversityOfHelsinkiCS/suoritustarkistin#274]
This is probably more an importer-sis-issue, but needs verification at Suotar-end as well.
These are courses used in Suotar that need checking:

~~AYBSCS1001 - Open uni: Introduction to programming // AYBSCS1001en is found, check if that can be used~~ (AYBSCS1001en was the correct one)
~~AYTKT50003en - Computing tools for CS Studies~~ Not a course
~~AYTKT50003 - Tietokone työvälineenä~~ Not a course
~~TKT50003 - Tietokone työvälineenä~~ Not a course
AY5823951 - Open uni: Cyber Security Base: Introduction to Cyber Security
AY5823952 - Open uni: Cyber Security Base: Securing Software
AY5823953 - Open uni: Cyber Security Base: Course Project I
AY5823954 - Open uni: Cyber Security Base: Advanced Topics
AY5823955 - Open uni: Cyber Security Base: Course Project II
AY5823856 - Open uni: Cyber Security Base: Capture The Flag

**Comment by vaahtokarkki** [comment]
See #355
