### ISSUE TITLE
Add new Kurki and partial courses to Suotar and make sure they have course units and realisations in SIS 

### ISSUE THREAD

**Issue by saarasat** [UniversityOfHelsinkiCS/suoritustarkistin#386]
**Kurki**
- TKT21002 - Introduction to Game Programming, 5 op, Juha Vihavainen
- CSM14206 - Game Engine Architecture, 5 op, Juha Vihavainen 
- CSM14204 - Compilers, 5 op, Juha Vihavainen 
- CSM14205 - Code Generation, 5 op, Juha Vihavainen
- CSM 13102 - Internet Protocols, 5 op, Markku Kojo
- CSM 13282 - Seminar: Advanced Topics in Networking and Security, 5 op, Markku Kojo
- TKT21026 - Network Programming, 5 op, Markku Kojo

**Partial courses**
- AYTKT21036en - DevOps with Docker, 1 op, Jami Kousa
- AYTKT21037en - DevOps with Docker: docker-compose, 1 op, Jami Kousa
- AYTKT21038en - DevOps with Docker: security and optimization, 1 op, Jami Kousa
- AYTKT200091en - CSB 1, 1 op, Nikolaj Tatti
- AYTKT200092en - CSB 2, 3 op, Nikolaj Tatti
- AYTKT200093en - CSB 3, 1 op, Nikolaj Tatti
- AYCSM132041en - CSB 4, 3 op, Nikolaj Tatti
- AYCSM132042en - CSB 5, 1 op, Nikolaj Tatti
- AYCSM132043en - CSB 6, 1 op, Nikolaj Tatti
- AYTKT210281en - The Elements of AI: Building AI - Intermediate, 1 op, Teemu Roos
- AYTKT210282en - The Elements of AI: Building AI - Advanced, 1 op, Teemu Roos
- AYCSM141081 - Full Stack -websovelluskehitys, 5 op, Matti Luukkainen
- AYCSM141082 - Full Stack -websovelluskehitys, lisäosa 1, 1 op, Matti Luukkainen
- AYCSM141083 - Full Stack -websovelluskehitys, lisäosa 2, 1 op, Matti Luukkainen 
- AYCSM141081en - Full Stack Web Development, 5 op, Matti Luukkainen 
- AYCSM141082en - Full Stack Web Development, extension 1, 1 op, Matti Luukkainen 
- AYCSM141083en - Full Stack Web Development, extension 2, 1 op, Matti Luukkainen

**Comment by vaahtokarkki** [comment]
Some graders still missing #401
