### ISSUE TITLE
Validate completion date against any of study rights when using erilliskirjaus

### ISSUE THREAD

**Issue by vaahtokarkki** [UniversityOfHelsinkiCS/suoritustarkistin#635]

**Comment by saarasat** [comment]
Got fixed in https://github.com/UniversityOfHelsinkiCS/suoritustarkistin/commit/b42cafe88ebb7c9a26be0fa965b9c648e6cb09cc, while doing https://github.com/UniversityOfHelsinkiCS/suoritustarkistin/issues/661
