### ISSUE TITLE
Wrong adjusted completion date

### ISSUE THREAD

**Issue by pllk** [UniversityOfHelsinkiCS/suoritustarkistin#658]
I noticed that Suotar changed the completion date to a wrong date. I think this is a problematic feature because I should not give a completion which states that the student has completed the course in 2018 (instead of 2022 when they actually completed the course). I had to manually remove this student from the csv file and send the file again.

![image](https://user-images.githubusercontent.com/901299/160229531-acff003c-39af-4b88-81f2-5f5fde98ea23.png)

**Comment by vaahtokarkki** [comment]
Fixed. In some cases, Suotar was referring to a wrong (deleted) version of the study right. Therefore the date correction did not work as it should.
