### ISSUE TITLE
Not yet visible in Sisu?

### ISSUE THREAD

**Issue by pllk** [UniversityOfHelsinkiCS/suoritustarkistin#659]
What does it mean that a completion is "not yet visible in Sisu"? Suotar should explain what will happen next: does it take 5 minutes or 2 weeks before the completion becomes visible, and should I do something myself to make it visible? 

![image](https://user-images.githubusercontent.com/901299/160229677-08a67583-1168-46a6-b0e9-5792f1d453f2.png)

**Comment by mluukkai** [comment]
Nowadays the completion is immediately visible in Sisu, so the text should be changed since it is currently misleading
