### ISSUE TITLE
Make it more visible when adjusting completion date to earlier date

### ISSUE THREAD

**Issue by qzuw** [UniversityOfHelsinkiCS/suoritustarkistin#738]
If a student has an enrollment to earlier course, but not current one, Suotar will happily adjust the completion date to even significantly earlier one. (IMO, it shouldn't do this, but I've been told there are reasons.)

The adjustment will only be signified by a small icon next to the date, with details visible on mouseover. This adjustment should be more visible so the teacher can decide whether to let it go through or tell the student to enroll to correct course.

At least a warning message and different background color (yellow?) to tell what is going on would be desirable.

(Personally I would like confirmation dialog with option also to treat these cases as missing enrollment, but this may not be suitable to workflow of others, and would probably require more work.)

Above issue does not apply to cases where the completion date is adjusted to later one due late enrollment, those are fine as is.

**Comment by Keskimaki** [comment]
![Screenshot from 2023-09-07 14-50-08](https://github.com/UniversityOfHelsinkiCS/suoritustarkistin/assets/87322574/618f0c44-af91-4c43-9ee3-9f49846024d6)

Now there is a warning message when dates have been changed
